import Head from 'next/head'
import CreateTaskForm from '../components/createForm'
import TodoList from '../components/todo-list'
import { useAuth0 } from "@auth0/auth0-react";
import { useRouter } from 'next/router'
import React from "react";


export default function Home() {
  const router = useRouter()

  const { user, isAuthenticated, isLoading } = useAuth0();


  if (isLoading) {
    return <div>Loading ...</div>;
  }

  if (!isAuthenticated) {
    return (
    <div style={{ marginTop: "70px"}}>
      <h2>Please log in to see your notes...</h2>
    </div>
    )
  }

  return (
    isAuthenticated && (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <CreateTaskForm user={user} />
      <TodoList user={user} />
      </div>
    )
  )
}
